web:
  replicas: 2
  image: ghcr.io/superpaigu/noteplatform:latest
  containerPort: 5000
  servicePort: 80

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

mysql:
  image: mysql:8.0
  servicePort: 3306
  storage: 1Gi

ingress:
  enabled: true